INSERT INTO dbpreparcial.tb_usuarios (carne, nombre, correo, seccion, activo) VALUES
('0905-18-4086', 'MARIO ANDRES CASTRO MORENO', 'mcastrom1@correo.example.com', 'A', 0),
('0905-19-9069', 'CARLA ISABEL MORENO TORO', 'cimoreno2@correo.example.com', 'A', 0),
('0905-21-10853', 'NATALIA ANDREA CASTAÑO REYES', 'ncastano3@correo.example.com', 'A', 0),
('0905-21-18067', 'DANIELA MARCELA MONTOYA SALGADO', 'dmontoya4@correo.example.com', 'A', 0),
('0905-22-11867', 'JUAN PABLO SALGADO VEGA', 'jpsalv5@correo.example.com', 'A', 0),
('0905-22-11875', 'ANDREA ALEJANDRA SALGADO VEGA', 'aasalv6@correo.example.com', 'A', 0),
('0905-23-1347', 'ALEJANDRO ANDRES CASTAÑO VALENCIA', 'aacastano7@correo.example.com', 'A', 0),
('0905-23-1624', 'SANTIAGO ANDRES TORO VALENCIA', 'satoro8@correo.example.com', 'A', 0),
('0905-23-3624', 'MARCELA ANDREA MOLINA VALENCIA', 'mmolina9@correo.example.com', 'A', 0),
('0905-23-3810', 'JULIAN ESTEBAN REYES MORENO', 'jerreyes0@correo.example.com', 'A', 0),
('0905-23-3930', 'DAVID ALEJANDRO MORENO TORO', 'dmoreno1@correo.example.com', 'A', 0),
('0905-23-4499', 'ANDREA ALEJANDRA MORENO SALGADO', 'aamoreno2@correo.example.com', 'A', 0),
('0905-23-4540', 'JUAN CAMILO VALENCIA TORO', 'jvalencia3@correo.example.com', 'A', 0),
('0905-23-4652', 'MARCELA ANDREA TORO MORENO', 'matoro4@correo.example.com', 'A', 0),
('0905-23-5026', 'JULIAN ANDRES SALGADO VALENCIA', 'jsalv5@correo.example.com', 'A', 0),
('0905-23-5027', 'ALEJANDRA MORENO CASTAÑO', 'amcastaño6@correo.example.com', 'A', 0),
('0905-23-5228', 'ISABEL CRISTINA VALENCIA TORO', 'icvalencia7@correo.example.com', 'A', 0),
('0905-23-5502', 'MARIA ALEJANDRA MOLINA REYES', 'mamolina8@correo.example.com', 'A', 0),
('0905-23-5576', 'LUIS ALEJANDRO MORENO SALGADO', 'lmoreno9@correo.example.com', 'A', 0),
('0905-23-6330', 'ANDREA MARCELA CASTAÑO REYES', 'acastano0@correo.example.com', 'A', 0),
('0905-23-6868', 'SERGIO ANDRES TORO MOLINA', 'storom1@correo.example.com', 'A', 0),
('0905-23-7313', 'JULIETA ANDREA SALGADO TORO', 'jsal0@correo.example.com', 'A', 0),
('0905-23-7627', 'ALEJANDRA MARCELA MORENO CASTAÑO', 'amc1@correo.example.com', 'A', 0),
('0905-23-10446', 'JUAN PABLO CASTAÑO MORENO', 'jpcastano2@correo.example.com', 'A', 0),
('0905-23-10737', 'CAROLINA ANDREA TORO MORENO', 'catoro3@correo.example.com', 'A', 0),
('0905-23-11866', 'ALEJANDRA ANDREA REYES SALGADO', 'aareyes4@correo.example.com', 'A', 0),
('0905-23-13244', 'JULIAN ANDRES MOLINA REYES', 'jmolina5@correo.example.com', 'A', 0),
('0905-23-14004', 'MARIA CAMILA CASTAÑO SALGADO', 'mccastaño6@correo.example.com', 'A', 0),
('0905-23-15375', 'ISABELLA ANDREA MORENO TORO', 'iandrea7@correo.example.com', 'A', 0),
('0905-23-15909', 'FRANCISCO JAVIER MORENO SALGADO', 'fjmoreno8@correo.example.com', 'A', 0),
('0905-23-17849', 'MARIA FERNANDA CASTAÑO REYES', 'mfcastano9@correo.example.com', 'A', 0),
('0905-23-19400', 'LUIS ALFONSO SALGADO VALENCIA', 'lasalv0@correo.example.com', 'A', 0),
('0905-23-21428', 'CAROLINA ANDREA CASTAÑO SALGADO', 'cacas0@correo.example.com', 'A', 0),
('0905-17-1080', 'SANDRA MILENA TORO SALGADO', 'smoreno1@correo.example.com', 'B', 0),
('0905-20-6301', 'JUAN ESTEBAN MORENO REYES', 'jemoreno2@correo.example.com', 'B', 0),
('0905-20-8465', 'MARIANA ANDREA CASTAÑO TORO', 'mcastano3@correo.example.com', 'B', 0),
('0905-21-10306', 'FERNANDO ALBERTO SALGADO MOLINA', 'falsal4@correo.example.com', 'B', 0),
('0905-21-15452', 'JENNIFER ANDREA REYES MORENO', 'jreyes5@correo.example.com', 'B', 0),
('0905-21-15473', 'DANIEL ANDRES MOLINA CASTAÑO', 'dandres6@correo.example.com', 'B', 0),
('0905-22-4502', 'ISABEL CRISTINA CASTAÑO MORENO', 'iccastano7@correo.example.com', 'B', 0),
('0905-22-6024', 'NATALIA REYES SALGADO', 'nreyes8@correo.example.com', 'B', 0),
('0905-22-21542', 'GABRIELA ANDREA TORO VALENCIA', 'gatoro9@correo.example.com', 'B', 0),
('0905-23-1438', 'VICTOR MANUEL MOLINA REYES', 'vmolina0@correo.example.com', 'B', 0),
('0905-23-4115', 'LUIS ALFONSO CASTAÑO SALGADO', 'lacastano1@correo.example.com', 'B', 0),
('0905-23-5035', 'ANA MARIA REYES TORO', 'amreyes2@correo.example.com', 'B', 0),
('0905-23-5325', 'CAROLINA CASTAÑO MOLINA', 'ccastano3@correo.example.com', 'B', 0);


INSERT INTO dbpreparcial.tb_datos (codigo, nombre, apellido, departamento, fecha_nacimiento) VALUES
(1, 'Juan', 'Pérez', 'Ventas', '1985-04-15'),
(2, 'María', 'Gómez', 'Marketing', '1990-07-20'),
(3, 'Luis', 'Martínez', 'IT', '1988-11-05'),
(4, 'Ana', 'Rodríguez', 'Recursos Humanos', '1992-01-12'),
(5, 'Carlos', 'Hernández', 'Contabilidad', '1984-09-28'),
(6, 'Laura', 'García', 'Logística', '1991-05-17'),
(7, 'José', 'Martínez', 'Ventas', '1987-03-22'),
(8, 'Sofía', 'Fernández', 'Marketing', '1993-08-30'),
(9, 'Miguel', 'López', 'IT', '1986-12-02'),
(10, 'Elena', 'Mendoza', 'Recursos Humanos', '1995-06-13'),
(11, 'Andrés', 'Castro', 'Contabilidad', '1983-10-07'),
(12, 'Paola', 'Pérez', 'Logística', '1989-02-19'),
(13, 'Ricardo', 'Torres', 'Ventas', '1984-07-25'),
(14, 'Valeria', 'Mora', 'Marketing', '1991-04-09'),
(15, 'Jorge', 'Serrano', 'IT', '1985-11-14'),
(16, 'Daniela', 'Mora', 'Recursos Humanos', '1992-09-23'),
(17, 'Oscar', 'Ramírez', 'Contabilidad', '1987-03-16'),
(18, 'Carmen', 'Gómez', 'Logística', '1990-08-12'),
(19, 'Felipe', 'Hernández', 'Ventas', '1986-12-20'),
(20, 'Gabriela', 'Rodríguez', 'Marketing', '1989-11-01'),
(21, 'Ricardo', 'Vargas', 'IT', '1988-04-05'),
(22, 'Silvia', 'García', 'Recursos Humanos', '1994-06-18'),
(23, 'Martín', 'Díaz', 'Contabilidad', '1983-07-28'),
(24, 'Nathalia', 'Salazar', 'Logística', '1991-03-22'),
(25, 'Fernando', 'Martínez', 'Ventas', '1985-05-14'),
(26, 'Isabel', 'Cano', 'Marketing', '1990-09-09'),
(27, 'Gustavo', 'Núñez', 'IT', '1987-02-11'),
(28, 'Mariana', 'Téllez', 'Recursos Humanos', '1993-10-16'),
(29, 'Samuel', 'Figueroa', 'Contabilidad', '1986-08-01'),
(30, 'Luisa', 'Cárdenas', 'Logística', '1988-12-25');


INSERT INTO dbpreparcial.equipos_champions (nombre, pais, ciudad, estadio, fundacion, entrenador, web_oficial, facebook, twitter, instagram, patrocinador_principal)
VALUES
    ('Real Solaris', 'España', 'Madrid', 'Estadio del Sol', 1902, 'Carlos Jiménez', 'https://www.realsolaris.com', 'https://facebook.com/realsolaris', 'https://twitter.com/realsolaris', 'https://instagram.com/realsolaris', 'Sol Energy'),
    ('Blue Ocean FC', 'Inglaterra', 'Londres', 'Ocean Stadium', 1998, 'David Williams', 'https://www.blueoceanfc.com', 'https://facebook.com/blueoceanfc', 'https://twitter.com/blueoceanfc', 'https://instagram.com/blueoceanfc', 'Oceanic Airlines'),
    ('AC Tempesta', 'Italia', 'Roma', 'Stadio Tempesta', 1921, 'Marco Rossi', 'https://www.actempesta.com', 'https://facebook.com/actempesta', 'https://twitter.com/actempesta', 'https://instagram.com/actempesta', 'Fiat'),
    ('Bayern Sturm', 'Alemania', 'Múnich', 'Stadion Sturm', 1905, 'Hans Müller', 'https://www.bayernsturm.de', 'https://facebook.com/bayernsturm', 'https://twitter.com/bayernsturm', 'https://instagram.com/bayernsturm', 'Allianz'),
    ('Paris Celeste', 'Francia', 'París', 'Stade Céleste', 1910, 'Jean-Pierre Blanc', 'https://www.parisceleste.fr', 'https://facebook.com/parisceleste', 'https://twitter.com/parisceleste', 'https://instagram.com/parisceleste', 'Air France'),
    ('Amsterdam Lions', 'Países Bajos', 'Ámsterdam', 'Lion Arena', 1917, 'Willem de Boer', 'https://www.amsterdamlions.nl', 'https://facebook.com/amsterdamlions', 'https://twitter.com/amsterdamlions', 'https://instagram.com/amsterdamlions', 'Heineken'),
    ('Lisbon Dragons', 'Portugal', 'Lisboa', 'Dragon Park', 1914, 'João Silva', 'https://www.lisbondragons.pt', 'https://facebook.com/lisbondragons', 'https://twitter.com/lisbondragons', 'https://instagram.com/lisbondragons', 'Sagres'),
    ('Zenith Moscow', 'Rusia', 'Moscú', 'Zenith Stadium', 1930, 'Sergei Ivanov', 'https://www.zenithmoscow.ru', 'https://facebook.com/zenithmoscow', 'https://twitter.com/zenithmoscow', 'https://instagram.com/zenithmoscow', 'Gazprom'),
    ('Ajax Valkyries', 'Suecia', 'Estocolmo', 'Valkyrie Arena', 1945, 'Erik Johansson', 'https://www.ajaxvalkyries.se', 'https://facebook.com/ajaxvalkyries', 'https://twitter.com/ajaxvalkyries', 'https://instagram.com/ajaxvalkyries', 'Volvo'),
    ('Celtic Phoenix', 'Escocia', 'Glasgow', 'Phoenix Park', 1987, 'Liam MacDonald', 'https://www.celticphoenix.co.uk', 'https://facebook.com/celticphoenix', 'https://twitter.com/celticphoenix', 'https://instagram.com/celticphoenix', 'Irn-Bru'),
    ('New York Titans', 'Estados Unidos', 'Nueva York', 'Titan Stadium', 1925, 'John Anderson', 'https://www.nytitans.com', 'https://facebook.com/nytitans', 'https://twitter.com/nytitans', 'https://instagram.com/nytitans', 'Nike'),
    ('São Paulo Thunder', 'Brasil', 'São Paulo', 'Thunder Dome', 1910, 'Carlos Oliveira', 'https://www.saopaulothunder.br', 'https://facebook.com/saopaulothunder', 'https://twitter.com/saopaulothunder', 'https://instagram.com/saopaulothunder', 'Petrobras'),
    ('Buenos Aires Gladiators', 'Argentina', 'Buenos Aires', 'Gladiator Arena', 1908, 'Miguel Pérez', 'https://www.buenosairesgladiators.ar', 'https://facebook.com/buenosairesgladiators', 'https://twitter.com/bagladiators', 'https://instagram.com/buenosairesgladiators', 'YPF'),
    ('Mexico City Warriors', 'México', 'Ciudad de México', 'Warrior Stadium', 1920, 'Juan Hernández', 'https://www.mexicocitywarriors.mx', 'https://facebook.com/mexicocitywarriors', 'https://twitter.com/mexicowarriors', 'https://instagram.com/mexicowarriors', 'Corona'),
    ('Toronto Blizzard', 'Canadá', 'Toronto', 'Blizzard Park', 1933, 'Robert Brown', 'https://www.torontoblizzard.ca', 'https://facebook.com/torontoblizzard', 'https://twitter.com/torontoblizzard', 'https://instagram.com/torontoblizzard', 'RBC'),
    ('Sydney Koalas', 'Australia', 'Sídney', 'Koala Stadium', 1950, 'Bruce Thompson', 'https://www.sydneykoalas.com.au', 'https://facebook.com/sydneykoalas', 'https://twitter.com/sydneykoalas', 'https://instagram.com/sydneykoalas', 'Qantas'),
    ('Tokyo Samurais', 'Japón', 'Tokio', 'Samurai Arena', 1927, 'Kenji Nakamura', 'https://www.tokyosamurais.jp', 'https://facebook.com/tokyosamurais', 'https://twitter.com/tokyosamurais', 'https://instagram.com/tokyosamurais', 'Sony'),
    ('Seoul Tigers', 'Corea del Sur', 'Seúl', 'Tiger Stadium', 1935, 'Park Ji-Sung', 'https://www.seoultigers.kr', 'https://facebook.com/seoultigers', 'https://twitter.com/seoultigers', 'https://instagram.com/seoultigers', 'Hyundai'),
    ('Cape Town Eagles', 'Sudáfrica', 'Ciudad del Cabo', 'Eagle Park', 1960, 'Sipho Dlamini', 'https://www.capetowneagles.za', 'https://facebook.com/capetowneagles', 'https://twitter.com/capetowneagles', 'https://instagram.com/capetowneagles', 'MTN'),
    ('Mumbai Royals', 'India', 'Mumbai', 'Royal Ground', 1975, 'Rajesh Patel', 'https://www.mumbairoyals.in', 'https://facebook.com/mumbairoyals', 'https://twitter.com/mumbairoyals', 'https://instagram.com/mumbairoyals', 'Reliance');
